/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym_management_system;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ZC
 */
public class Trainer_Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Trainer_Home_PAge
     */
    public Trainer_Home_Page() {
        initComponents();
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        attendancerButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        memberDetailsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        gymPackageButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        packageButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        memberListButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        welcomeLabel.setText("WELCOME");
        jPanel1.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 320, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("TO trainer page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        attendancerButton.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        attendancerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/immigration (1).png"))); // NOI18N
        attendancerButton.setText("Attendance");
        attendancerButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        attendancerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendancerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendancerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendancerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 153, 220, 90));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 163, -1, 125));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 163, -1, -1));

        memberDetailsButton.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        memberDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/resume.png"))); // NOI18N
        memberDetailsButton.setText("Members Details");
        memberDetailsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        memberDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberDetailsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(memberDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 220, 90));

        exitButton.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        exitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 220, 80));

        gymPackageButton.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        gymPackageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/package (1).png"))); // NOI18N
        gymPackageButton.setText("Gym Packages");
        gymPackageButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        gymPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymPackageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gymPackageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 220, 90));

        jButton1.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rating_1.png"))); // NOI18N
        jButton1.setText("Gym Review");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 230, 90));

        packageButton.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        packageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/checklist (1).png"))); // NOI18N
        packageButton.setText("Package List");
        packageButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        packageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(packageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 220, 90));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memberListButton.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        memberListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/members.png"))); // NOI18N
        memberListButton.setText("Members List");
        memberListButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        memberListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberListButtonActionPerformed(evt);
            }
        });
        jPanel5.add(memberListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 90));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 230, 90));

        jButton2.setFont(new java.awt.Font("ArhialkhanGMJ", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/immigration (1).png"))); // NOI18N
        jButton2.setText("Attendence List");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 230, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendancerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendancerButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Gym_Member_Attendence attendence=new Gym_Member_Attendence();
        attendence.setVisible(true);
    }//GEN-LAST:event_attendancerButtonActionPerformed

    private void memberDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberDetailsButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Member_Details_See_Trainer details=new Member_Details_See_Trainer();
        details.setVisible(true);
    }//GEN-LAST:event_memberDetailsButtonActionPerformed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        int close=JOptionPane.showConfirmDialog(null,"Do you really want to Exit Application","Selet",JOptionPane.YES_NO_OPTION);
        if(close==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
         int close=JOptionPane.showConfirmDialog(null,"Do you really want to Exit Application","Selet",JOptionPane.YES_NO_OPTION);
        if(close==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void memberListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberListButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       Member_List_See_Trainer list=new Member_List_See_Trainer();
        list.setVisible(true);
    }//GEN-LAST:event_memberListButtonActionPerformed

    private void gymPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymPackageButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       Gym_Packages_Trainer pack=new Gym_Packages_Trainer();
        pack.setVisible(true);
    }//GEN-LAST:event_gymPackageButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       Gym_Review review=new Gym_Review();
        review.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void packageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
       Package_List_Trainer list=new Package_List_Trainer();
        list.setVisible(true);
        
    }//GEN-LAST:event_packageButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       setVisible(false);
       Gym_Member_Attendence_List  memberList=new Gym_Member_Attendence_List();
        memberList.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trainer_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trainer_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trainer_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trainer_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trainer_Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendancerButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gymPackageButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton memberDetailsButton;
    private javax.swing.JButton memberListButton;
    private javax.swing.JButton packageButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
